# Generated by Django 4.1.3 on 2024-10-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeira_api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
